# tasks/base.yml - applies to all hosts
---
- name: Set timezone to UTC
  timezone:
    name: Europe/Athens

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - wget
      - htop
    state: present

- name: Ensure lightdm directory exists
  ansible.builtin.file:
    path: /etc/lightdm
    state: directory
    mode: '0755'

- name: Configure slick-greeter settings
  community.general.ini_file:
    path: /etc/lightdm/slick-greeter.conf
    section: Greeter
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
    mode: '0644'
  loop:
    - { option: 'show-hostname', value: 'true' }
    - { option: 'hidden-users', value: 'false' }
        
- name: Configure slick-lightdm
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: Seat:*
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
    mode: '0644'
  loop:
    - { option: 'greeter-hide-users', value: 'true' }

- name: Set up cron job for ansible-pull
  cron:
    name: "Ansible Pull Workstation Config"
    minute: "*/30" # Runs every 30 minutes
    job: "ansible-pull -U https://github.com/uowmnoc/workstation-config.git > /var/log/ansible-pull.log 2>&1"
    user: root
